
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package RegexParser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LAZY_PLUS = 22;
  public static final int LBRACKET = 31;
  public static final int NOTDIGIT = 17;
  public static final int NON_CAPTURE = 42;
  public static final int POSSESSIVE_PLUS = 21;
  public static final int METANOTBOUNDARY = 7;
  public static final int LPAREN = 33;
  public static final int GREEDY_STAR = 23;
  public static final int MINUS = 18;
  public static final int METAVERTICALTAB = 12;
  public static final int METAFEED = 5;
  public static final int RPAREN = 34;
  public static final int ESCAPEDCHAR = 15;
  public static final int ATOMIC_GROUP = 41;
  public static final int METABOUNDARY = 6;
  public static final int COMMA = 38;
  public static final int GREEDY_PLUS = 20;
  public static final int METADIGIT = 8;
  public static final int METANEWLINE = 3;
  public static final int METANOTSPACE = 11;
  public static final int DIGIT = 16;
  public static final int CARET = 29;
  public static final int DOT = 19;
  public static final int EOF = 0;
  public static final int RBRACKET = 32;
  public static final int error = 1;
  public static final int LCURLY = 35;
  public static final int GREEDY_OPTIONAL = 26;
  public static final int METARETURN = 4;
  public static final int RCURLY = 36;
  public static final int LAZY_OPTIONAL = 28;
  public static final int UNION = 37;
  public static final int POSSESSIVE_OPTIONAL = 27;
  public static final int DOLLAR = 30;
  public static final int METANOTDIGIT = 9;
  public static final int METATAB = 2;
  public static final int METAWORD = 13;
  public static final int METANOTWORD = 14;
  public static final int NEG_LOOKAHEAD = 40;
  public static final int LAZY_STAR = 25;
  public static final int POS_LOOKAHEAD = 39;
  public static final int METASPACE = 10;
  public static final int POSSESSIVE_STAR = 24;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "METATAB",
  "METANEWLINE",
  "METARETURN",
  "METAFEED",
  "METABOUNDARY",
  "METANOTBOUNDARY",
  "METADIGIT",
  "METANOTDIGIT",
  "METASPACE",
  "METANOTSPACE",
  "METAVERTICALTAB",
  "METAWORD",
  "METANOTWORD",
  "ESCAPEDCHAR",
  "DIGIT",
  "NOTDIGIT",
  "MINUS",
  "DOT",
  "GREEDY_PLUS",
  "POSSESSIVE_PLUS",
  "LAZY_PLUS",
  "GREEDY_STAR",
  "POSSESSIVE_STAR",
  "LAZY_STAR",
  "GREEDY_OPTIONAL",
  "POSSESSIVE_OPTIONAL",
  "LAZY_OPTIONAL",
  "CARET",
  "DOLLAR",
  "LBRACKET",
  "RBRACKET",
  "LPAREN",
  "RPAREN",
  "LCURLY",
  "RCURLY",
  "UNION",
  "COMMA",
  "POS_LOOKAHEAD",
  "NEG_LOOKAHEAD",
  "ATOMIC_GROUP",
  "NON_CAPTURE"
  };
}

